listen-address=0.0.0.0
bind-interfaces

local=/admv.test/
host-record=app.admv.test,10.7.23.71
host-record=api.admv.test,10.7.23.71
local-ttl=30

no-resolv
server=8.8.8.8
server=1.1.1.1
domain-needed
bogus-priv

log-queries
log-facility=/tmp/dnsmasq.log